services:
  - type: web
    name: iris-fastapi
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.api.main:app --host 0.0.0.0 --port 8000"
    env: python
